services:
  - name: gym-backend
    type: web
    plan: free
    runtime: docker
    rootDir: gymmanagement
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d1mkoqffte5s73ce7p50-a.oregon-postgres.render.com/gym_app_5i95
      - key: DB_USER
        value: ganesh
      - key: DB_PASSWORD
        value: z5aj8BQkwcncjvdf0lN0Qp7cRU94xPAe
      - key: SECRET_TOKEN_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  - name: gym-frontend
    type: web
    plan: free
    runtime: node
    rootDir: react-app-gym
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://gym-backend-0i84.onrender.com
