# render.yaml - CORRECTED VERSION
# Deploys a Spring Boot + React monorepo on Render

services:
  # Service 1: The PostgreSQL Database
  - type: pserv
    name: gym-database
    env: postgres
    plan: free
    # Note: Free databases on Render expire after 90 days.

  # Service 2: The Spring Boot Backend
  - type: web
    name: gym-backend
    env: java
    rootDir: gymmanagement # Directory for your Spring Boot app
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/gymmanagement-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        fromDatabase:
          name: gym-database
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: gym-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gym-database
          property: password
      # Add the following secrets in the Render Dashboard, NOT here.
      - key: SECRET_TOKEN_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  # Service 3: The React Frontend (as a Static Site)
  - type: static_site # CORRECTED: "static_site" is the right type
    name: gym-frontend
    rootDir: react_app_gym # CORRECTED: to match your folder name
    plan: free
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: gym-backend
          property: url